version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'monthly'
  # Keep dockerfile up-to-date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: 'monthly'
